version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-store-api
    container_name: app-store-api
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production